services:
  annual-report-mcp:
    image: jorbenzhu/mcp-annual-report:latest
    ports:
      - 4200:4200
    environment:
      - MCP_AUTH_TOKEN=pls-change-me
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - LC_CTYPE=en_US.UTF-8
      - PYTHONIOENCODING=utf-8
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
    restart: always
